package com.br.pdftogether.gui;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import org.apache.pdfbox.multipdf.PDFMergerUtility;

/**
 *
 * @author juliomiguel
 */
public class MainFrame extends javax.swing.JFrame {
     
    private DefaultListModel<String> availableSongsListModel;
    private DefaultListModel<String> addedSongsListModel;
    private File songsDirectory = new File(System.getProperty("user.dir") + "/pdfs");
   
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setDefaultModelToListsComponents();
        this.listPdfFiles();
        
    }
    
    private void listPdfFiles() {
        File[] pdfsSongs = this.songsDirectory.listFiles();
            
        for (File pdfSong : pdfsSongs) {
            String fileName = pdfSong.getName();
            if (!fileName.contains(".pdf")) {
                continue;
            }
            this.availableSongsListModel.addElement(pdfSong.getName());
        }   
    }
    
    private void setDefaultModelToListsComponents() {
        this.availableSongsListModel = new DefaultListModel();
        this.addedSongsListModel = new DefaultListModel();
        this.availableSongs.setModel(availableSongsListModel);
        this.addedSongs.setModel(addedSongsListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblAvailablePdfs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableSongs = new javax.swing.JList<>();
        lblAddedPdfs = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addedSongs = new javax.swing.JList<>();
        bntMergePdfs = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDF Together");

        bg.setBackground(new java.awt.Color(63, 72, 75));

        jPanel1.setBackground(new java.awt.Color(49, 56, 59));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PDF-Together.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(216, 216, 216))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblAvailablePdfs.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lblAvailablePdfs.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailablePdfs.setText("PDFs DISPONÍVEIS");

        availableSongs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                availableSongsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(availableSongs);

        lblAddedPdfs.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lblAddedPdfs.setForeground(new java.awt.Color(255, 255, 255));
        lblAddedPdfs.setText("PDFs ADICIONADOS");

        addedSongs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addedSongsMousePressed(evt);
            }
        });
        addedSongs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addedSongsKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(addedSongs);

        bntMergePdfs.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bntMergePdfs.setText("Juntar");
        bntMergePdfs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntMergePdfsMouseClicked(evt);
            }
        });
        bntMergePdfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMergePdfsActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField1.setText("Pesquisar");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lblAvailablePdfs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddedPdfs)
                .addGap(149, 149, 149))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(bntMergePdfs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailablePdfs)
                    .addComponent(lblAddedPdfs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(bntMergePdfs, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bntMergePdfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMergePdfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntMergePdfsActionPerformed

    private void bntMergePdfsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntMergePdfsMouseClicked
        PDFMergerUtility PDFMerger = new PDFMergerUtility();
        String appPath = System.getProperty("user.dir");
        String PDFDestination = appPath + "-mergedPDF.pdf";
        PDFMerger.setDestinationFileName(PDFDestination);
        for (int i = 0; i < this.addedSongsListModel.getSize(); i++) {
            String pdfName = this.addedSongsListModel.getElementAt(i);
            String filePath = this.songsDirectory + "/" + pdfName;
            try {
                PDFMerger.addSource(filePath);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,ex.toString());
            }
        }

        try {
            PDFMerger.mergeDocuments();
            JOptionPane.showMessageDialog(null, "PDFs juntados com sucesso!");
            File pdfDir = new File(appPath);
            Desktop.getDesktop().open(pdfDir);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_bntMergePdfsMouseClicked

    private void addedSongsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addedSongsKeyPressed
        boolean deleteKeyPressed = evt.getKeyCode() == KeyEvent.VK_DELETE;
        if (deleteKeyPressed) {
            int selectedIndex = addedSongs.getSelectedIndex();
            if (selectedIndex != -1) {
                this.addedSongsListModel.remove(selectedIndex);
            }
        }
    }//GEN-LAST:event_addedSongsKeyPressed

    private void addedSongsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addedSongsMousePressed
        if (!SwingUtilities.isRightMouseButton(evt)) {
            return;
        }

        this.showContextMenu(evt);
    }//GEN-LAST:event_addedSongsMousePressed

    private void availableSongsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_availableSongsValueChanged
        if (!evt.getValueIsAdjusting()) {
            Object selectedItem = this.availableSongs.getSelectedValue();
            Boolean containsElement = this.addedSongsListModel
            .contains(selectedItem);

            if (!containsElement) {
                this.addedSongsListModel.addElement(selectedItem.toString());
            }

        }
    }//GEN-LAST:event_availableSongsValueChanged

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        AboutFrame aboutFrame = new AboutFrame();
        aboutFrame.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked
    
    private void showContextMenu(MouseEvent e) {
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem removeItem = new JMenuItem("Remover Item");
        popupMenu.add(removeItem);
        popupMenu.show(e.getComponent(), e.getX(), e.getY());
        removeItem.addActionListener((ActionEvent ae) -> {
            this.addedSongsListModel.remove(this.addedSongs.getSelectedIndex());
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> addedSongs;
    private javax.swing.JList<String> availableSongs;
    private javax.swing.JPanel bg;
    private javax.swing.JButton bntMergePdfs;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAddedPdfs;
    private javax.swing.JLabel lblAvailablePdfs;
    // End of variables declaration//GEN-END:variables
}

