package gui;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import org.apache.pdfbox.multipdf.PDFMergerUtility;

/**
 *
 * @author juliomiguel
 */
public class MainFrame extends javax.swing.JFrame {
    
    ImageIcon searchIcon = new ImageIcon(getClass().getResource("/search.png") );
    
    private DefaultListModel<String> availableSongsListModel;
    private DefaultListModel<String> addedSongsListModel;
    private File songsDirectory = new File(System.getProperty("user.dir") + "/pdfs");
   
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setDefaultModelToListsComponents();
        this.listPdfFiles();
        this.lblSearchIcon.setIcon(searchIcon);
    }
    
    private void listPdfFiles() {
        File[] pdfsSongs = this.songsDirectory.listFiles();
            
        for (File pdfSong : pdfsSongs) {
            String fileName = pdfSong.getName();
            if (!fileName.contains(".pdf")) {
                continue;
            }
            this.availableSongsListModel.addElement(pdfSong.getName());
        }   
    }
    
    private void setDefaultModelToListsComponents() {
        this.availableSongsListModel = new DefaultListModel();
        this.addedSongsListModel = new DefaultListModel();
        this.availableSongs.setModel(availableSongsListModel);
        this.addedSongs.setModel(addedSongsListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAvailablePdfs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableSongs = new javax.swing.JList<>();
        lblAddedPdfs = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addedSongs = new javax.swing.JList<>();
        bntMergePdfs = new javax.swing.JButton();
        lblSearchIcon = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDF Together");

        bg.setBackground(new java.awt.Color(63, 72, 75));

        jPanel1.setBackground(new java.awt.Color(49, 56, 59));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PDF Together.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblAvailablePdfs.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lblAvailablePdfs.setForeground(new java.awt.Color(255, 255, 255));
        lblAvailablePdfs.setText("PDFs DISPONÍVEIS");

        availableSongs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                availableSongsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(availableSongs);

        lblAddedPdfs.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lblAddedPdfs.setForeground(new java.awt.Color(255, 255, 255));
        lblAddedPdfs.setText("PDFs ADICIONADOS");

        addedSongs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addedSongsMousePressed(evt);
            }
        });
        addedSongs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addedSongsKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(addedSongs);

        bntMergePdfs.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bntMergePdfs.setText("Juntar");
        bntMergePdfs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntMergePdfsMouseClicked(evt);
            }
        });
        bntMergePdfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMergePdfsActionPerformed(evt);
            }
        });

        lblSearchIcon.setText("ico");
        lblSearchIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchIconMouseClicked(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jTextField1.setText("Pesquisar");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(lblAvailablePdfs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddedPdfs)
                .addGap(124, 124, 124))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(lblSearchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(bntMergePdfs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblAvailablePdfs))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblAddedPdfs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntMergePdfs, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        jMenu1.setText("PDFs Files");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSearchIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchIconMouseClicked
        JOptionPane.showMessageDialog(null, "Funcionalidade indisponível nesta release");
    }//GEN-LAST:event_lblSearchIconMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bntMergePdfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMergePdfsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntMergePdfsActionPerformed

    private void bntMergePdfsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntMergePdfsMouseClicked
        PDFMergerUtility PDFMerger = new PDFMergerUtility();
        String appPath = System.getProperty("user.dir");
        String PDFDestination = appPath + "-mergedPDF.pdf";
        PDFMerger.setDestinationFileName(PDFDestination);
        for (int i = 0; i < this.addedSongsListModel.getSize(); i++) {
            String pdfName = this.addedSongsListModel.getElementAt(i);
            String filePath = this.songsDirectory + "/" + pdfName;
            try {
                PDFMerger.addSource(filePath);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,ex.toString());
            }
        }

        try {
            PDFMerger.mergeDocuments();
            JOptionPane.showMessageDialog(null, "PDFs juntados com sucesso!");
            File pdfDir = new File(appPath);
            Desktop.getDesktop().open(pdfDir);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex.toString());
        }
    }//GEN-LAST:event_bntMergePdfsMouseClicked

    private void addedSongsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addedSongsKeyPressed
        boolean deleteKeyPressed = evt.getKeyCode() == KeyEvent.VK_DELETE;
        if (deleteKeyPressed) {
            int selectedIndex = addedSongs.getSelectedIndex();
            if (selectedIndex != -1) {
                this.addedSongsListModel.remove(selectedIndex);
            }
        }
    }//GEN-LAST:event_addedSongsKeyPressed

    private void addedSongsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addedSongsMousePressed
        if (!SwingUtilities.isRightMouseButton(evt)) {
            return;
        }

        this.showContextMenu(evt);
    }//GEN-LAST:event_addedSongsMousePressed

    private void availableSongsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_availableSongsValueChanged
        if (!evt.getValueIsAdjusting()) {
            Object selectedItem = this.availableSongs.getSelectedValue();
            Boolean containsElement = this.addedSongsListModel
            .contains(selectedItem);

            if (!containsElement) {
                this.addedSongsListModel.addElement(selectedItem.toString());
            }

        }
    }//GEN-LAST:event_availableSongsValueChanged

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        AboutFrame aboutFrame = new AboutFrame();
        aboutFrame.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked
    
    private void showContextMenu(MouseEvent e) {
        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem removeItem = new JMenuItem("Remover Item");
        popupMenu.add(removeItem);
        popupMenu.show(e.getComponent(), e.getX(), e.getY());
        removeItem.addActionListener((ActionEvent ae) -> {
            this.addedSongsListModel.remove(this.addedSongs.getSelectedIndex());
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> addedSongs;
    private javax.swing.JList<String> availableSongs;
    private javax.swing.JPanel bg;
    private javax.swing.JButton bntMergePdfs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAddedPdfs;
    private javax.swing.JLabel lblAvailablePdfs;
    private javax.swing.JLabel lblSearchIcon;
    // End of variables declaration//GEN-END:variables
}

